### ISSUE TITLE
Issue with next.js / expo

### ISSUE THREAD

**Issue by shamoons** [akveo/react-native-ui-kitten#1058]
## To Reproduce

My `package.json` has:
```
  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.4",
    "@eva-design/eva": "^1.4.0",
    "@ui-kitten/components": "^4.4.1",
    "@ui-kitten/eva-icons": "^4.4.1",
    "aws-amplify": "^3.0.9",
    "expo-font": "^8.1.1",
    "next": "9.3.6",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-native": "^0.62.2",
    "react-native-svg": "~9.13.3",
    "react-native-web": "^0.12.2"
  },
  "devDependencies": {
    "@expo/next-adapter": "^2.1.2",
    "babel-preset-expo": "^8.1.0",
    "next-transpile-modules": "^3.2.0"
  }
```

My `pages/_app.tsx` has:
```
import App from 'next/app'
import * as eva from '@eva-design/eva';
import { ApplicationProvider } from '@ui-kitten/components';

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props
    return <ApplicationProvider {...eva} theme={eva.light}><Component {...pageProps} /></ApplicationProvider>
  }
}

export default MyApp
```

## Expected behavior

I expect it to work, instead I get an error:
```
node_modules/react-native/index.js:13
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
       ^^^^^^

SyntaxError: Unexpected token typeof
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

```bash

```

**Comment by artyorsh** [comment]
```
node_modules/react-native/index.js:13
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
```

UI Kitten has no common with AccessibilityInfo, try submitting the issue in react-native (Expo, if you use it) repo, since the error is occurred on their's module.
