### ISSUE TITLE
rkModalImg.js syntax error 

### ISSUE THREAD

**Issue by arshidkv12** [akveo/react-native-ui-kitten#133]
Not working in ubuntu 
```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"type":"TransformError","lineNumber":277,"column":17,"filename":"/home/arshid/Desktop/shopdummy/shopdummy/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js","errors":[{"description":"SyntaxError: /home/arshid/Desktop/shopdummy/shopdummy/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js: A trailing comma is not permitted after the rest element (277:17)\n\n  275 |       index,\n  276 |       style: imgStyle,\n> 277 |       ...imgProps,\n      |                  ^\n  278 |     } = this.props;\n  279 | \n  280 |     let {","filename":"/home/arshid/Desktop/shopdummy/shopdummy/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js","lineNumber":277}],"name":"SyntaxError","message":"SyntaxError: /home/arshid/Desktop/shopdummy/shopdummy/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js: A trailing comma is not permitted after the rest element (277:17)\n\n  275 |       index,\n  276 |       style: imgStyle,\n> 277 |       ...imgProps,\n      |                  ^\n  278 |     } = this.props;\n  279 | \n  280 |     let {","stack":"SyntaxError: /home/arshid/Desktop/shopdummy/shopdummy/node_modules/react-native-ui-kitten/src/components/image/rkModalImg.js: A trailing comma is not permitted after the rest element (277:17)\n\n  275 |       index,\n  276 |       style: imgStyle,\n> 277 |       ...imgProps,\n      |                  ^\n  278 |     } = this.props;\n  279 | \n  280 |     let {\n    at _class.raise (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:776:15)\n    at _class.unexpected (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:2079:16)\n    at _class.parseObj (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:3510:18)\n    at _class.parseBindingAtom (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:2336:21)\n    at _class.parseVarHead (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:4603:20)\n    at _class.parseVarHead (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:7277:42)\n    at _class.parseVar (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:4579:12)\n    at _class.parseVarStatement (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:4412:10)\n    at _class.parseStatementContent (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:4012:21)\n    at _class.parseStatement (/home/arshid/Desktop/shopdummy/shopdummy/node_modules/@babel/core/node_modules/babylon/lib/index.js:3962:17)"}
processBundleResult
    BundleDownloader.java:285
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:163
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764
```

-->

### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report

### Issue description

**Current behavior:**
Not running 

**Expected behavior:**
I want add nativebase and kitten ui.

### Other information:

Ubuntu : 16.04 
native-base: 2.7.2,
react : 16.4.1,
react-native: 0.56.0,

**Comment by artyorsh** [comment]
Hi @arshidkv12,
Thanks for report. This is occurred because of your project RN version.
You can refer to [this issue](https://github.com/akveo/react-native-ui-kitten/issues/129#issuecomment-408483828)
