### ISSUE TITLE
react-native run-ios and react-native run-android commands fail

### ISSUE THREAD

**Issue by ZoltanSzokodi** [akveo/react-native-ui-kitten#1642]
Hi, 

when I try to run `react-native run-ios` or `react-native run-android` from my project folder in VSCode I get the following error:

```
error Cannot read properties of undefined (reading 'configurations').
TypeError: Cannot read properties of undefined (reading 'configurations')
    at Object.dependencyConfig (/Users/user/Desktop/company/app/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)
    at /Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/@react-native-community/cli/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/@react-native-community/cli/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)
    at Object.get @eva-design/eva [as @eva-design/eva] (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/@react-native-community/cli/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)
    at warnAboutManuallyLinkedLibs (/Users/user/Desktop/company/app/node_modules/@react-native-community/cli-platform-ios/build/link/warnAboutManuallyLinkedLibs.js:39:43)
    at Object.runIOS [as func] (/Users/user/Desktop/company/app/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:104:44)
    at Command.handleAction (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/@react-native-community/cli/build/index.js:192:23)
    at Command.listener (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/@react-native-community/cli/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:527:28)
info Run CLI with --verbose flag for more details.
```

However if I start the app in XCode it builds successfully. After some research I found the modifying the _node_modules/@react-native-community/cli-platform-ios/build/config/index.js_ fixes the problem:

```
function dependencyConfig(folder, userConfig) {
// const configurations = userConfig.configurations || [];
    let configurations="";
    const baseConfig = projectConfig(folder, userConfig);
...
```
(source: https://stackoverflow.com/questions/72479193/error-cannot-read-properties-of-undefined-reading-configurations-typeerror)

However this is super sketchy and I'd rather not patch the package. Any ideas what could be the problem here?

**Comment by ZoltanSzokodi** [comment]
I think the UI-kitten installation template needs some care. RN 0.64.1 is a bit outdated for a new project. I've upgraded to 0.69.4 and now it's fine.
