### ISSUE TITLE
Installing ui-kitten give me npm version error 

### ISSUE THREAD

**Issue by vitoo** [akveo/react-native-ui-kitten#19]
Hello,

I have node v8.0.0
npm v4.6.1

Here is what i'm doing : 

```
create-react-native-app AwesomeProject
cd AwesomeProject
npm start
*it works, expo start*
``` 
Then
`npm install --save react-native-ui-kitten`
I got : 

```
Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.4. Please use an npm version that is >= 3.0.0 and < 5.0.0.
17:38:39: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at Generator.next (<anonymous>)
    at step (/var/www_repo/kheyfinder_client/reactnat/node_modules/xdl/build/Project.js:1468:191)
    at /var/www_repo/kheyfinder_client/reactnat/node_modules/xdl/build/Project.js:1468:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vito/.npm/_logs/2017-07-02T15_38_39_075Z-debug.log

```
Link to complete log : https://gist.github.com/vitoo/8834670146e120a3c86fa231b5fc05da

If i do `npm remove react-native-ui-kitten` it works again :/ 

Any idea why i got this ? =/

**Comment by csbok** [comment]
I also faced this problem.
below link will be help you.

https://github.com/react-community/create-react-native-app/issues/277#issuecomment-312439858

solve : you told me, you are already use npm 4.6.1 (globally. right?)
but you need to `npm install npm@4.6.1` in your create-react-native-app project directory in locally.

**Comment by vitoo** [comment]
The thing is i'm actually in 4.6.1 (me and the sudo account)
