### ISSUE TITLE
Packager failing to start after installation (create-react-native-app)

### ISSUE THREAD

**Issue by mikehamil10** [akveo/react-native-ui-kitten#21]
If you start a new project with crna then do an npm (or yarn, I tried both) installation of react-native-ui-kitten, the packager (and subsequently the app itself), stop working. The exact error message is:

`yarn start v0.27.5
$ react-native-scripts start
12:42:40 PM: Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.4. Please use an npm version that is >= 3.0.0 and < 5.0.0.
12:42:41 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at next (native)
    at step (/Users/mike/Developer/clubready/presentation-viewer/node_modules/xdl/build/Project.js:1468:191)
    at /Users/mike/Developer/clubready/presentation-viewer/node_modules/xdl/build/Project.js:1468:361
error Command failed with exit code 1.`

This issue led to believe there was something wrong with my Node/NPM installation, so I completely uninstalled and re-installed the LTS version. My node is 6.11.0 and my NPM is 3.10.10 (so I have NO idea why the error message says I'm using npm 5.0.4).

Simply uninstalling the package again fixes everything, which is unfortunate because I'm unable to use this library entirely.

**Comment by mikehamil10** [comment]
OK, I just realized that this is duplicate of https://github.com/akveo/react-native-ui-kitten/issues/19, and it is resolvable by simply doing an `npm install npm@4.6.1` WITHIN the project folder.

This is obviously a problem if 2 people have opened issues for it in as many days, hopefully it gets sorted at some point...
