### ISSUE TITLE
install.js does not exist in react-native-template-ui-kitten-typescript

### ISSUE THREAD

**Issue by androidjaijai** [akveo/react-native-ui-kitten#618]
I tried to initialize the project using `react-native init UiKittenTS --template ui-kitten-typescript` but got the error below
```
Using yarn v1.17.3
Installing react-native...
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.54.1" has unmet peer dependency "@babel/core@*".
warning " > react-native@0.60.5" has unmet peer dependency "react@16.8.6".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 391 new dependencies.
info Direct dependencies
└─ react-native@0.60.5
info All dependencies
├─ @babel/generator@7.6.0
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.1.0
├─ @babel/helper-builder-react-jsx@7.3.0
├─ @babel/helper-call-delegate@7.4.4
├─ @babel/helper-create-class-features-plugin@7.6.0
├─ @babel/helper-define-map@7.5.5
├─ @babel/helper-explode-assignable-expression@7.1.0
├─ @babel/helper-hoist-variables@7.4.4
├─ @babel/helper-module-transforms@7.5.5
├─ @babel/helper-regex@7.5.5
├─ @babel/helper-remap-async-to-generator@7.1.0
├─ @babel/helper-wrap-function@7.2.0
├─ @babel/helpers@7.6.0
├─ @babel/highlight@7.5.0
├─ @babel/parser@7.6.0
├─ @babel/plugin-external-helpers@7.2.0
├─ @babel/plugin-proposal-export-default-from@7.5.2
├─ @babel/plugin-syntax-class-properties@7.2.0
├─ @babel/plugin-syntax-dynamic-import@7.2.0
├─ @babel/plugin-syntax-export-default-from@7.2.0
├─ @babel/plugin-syntax-nullish-coalescing-operator@7.2.0
├─ @babel/plugin-syntax-object-rest-spread@7.2.0
├─ @babel/plugin-syntax-optional-catch-binding@7.2.0
├─ @babel/plugin-syntax-optional-chaining@7.2.0
├─ @babel/plugin-syntax-typescript@7.3.3
├─ @babel/plugin-transform-async-to-generator@7.5.0
├─ @babel/plugin-transform-block-scoped-functions@7.2.0
├─ @babel/plugin-transform-exponentiation-operator@7.2.0
├─ @babel/plugin-transform-member-expression-literals@7.2.0
├─ @babel/plugin-transform-object-assign@7.2.0
├─ @babel/plugin-transform-object-super@7.5.5
├─ @babel/plugin-transform-property-literals@7.2.0
├─ @babel/plugin-transform-react-jsx-source@7.5.0
├─ @babel/plugin-transform-regenerator@7.4.5
├─ @babel/plugin-transform-runtime@7.6.0
├─ @babel/plugin-transform-sticky-regex@7.2.0
├─ @babel/plugin-transform-typescript@7.6.0
├─ @babel/plugin-transform-unicode-regex@7.4.4
├─ @babel/register@7.6.0
├─ @babel/runtime@7.6.0
├─ @cnakazawa/watch@1.0.3
├─ @hapi/address@2.1.1
├─ @hapi/bourne@1.3.2
├─ @hapi/joi@15.1.1
├─ @hapi/topo@3.1.3
├─ @jest/fake-timers@24.9.0
├─ @react-native-community/cli-platform-android@2.9.0
├─ @react-native-community/cli-platform-ios@2.9.0
├─ @react-native-community/cli@2.9.0
├─ @types/istanbul-lib-report@1.1.1
├─ @types/istanbul-reports@1.1.1
├─ @types/stack-utils@1.0.1
├─ @types/yargs-parser@13.1.0
├─ @types/yargs@13.0.2
├─ abort-controller@3.0.0
├─ accepts@1.3.7
├─ ansi-colors@1.1.0
├─ ansi-cyan@0.1.1
├─ ansi-escapes@3.2.0
├─ ansi-fragments@0.2.1
├─ ansi-gray@0.1.1
├─ ansi-red@0.1.1
├─ ansi-regex@4.1.0
├─ argparse@1.0.10
├─ arr-flatten@1.1.0
├─ array-filter@0.0.1
├─ array-map@0.0.0
├─ array-reduce@0.0.0
├─ array-slice@0.2.3
├─ art@0.10.3
├─ asap@2.0.6
├─ assign-symbols@1.0.0
├─ astral-regex@1.0.0
├─ async-limiter@1.0.1
├─ async@2.6.3
├─ atob@2.1.2
├─ babel-plugin-dynamic-import-node@2.3.0
├─ babel-plugin-syntax-trailing-function-commas@7.0.0-beta.0
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ base64-js@1.3.1
├─ basic-auth@2.0.1
├─ big-integer@1.6.45
├─ bplist-creator@0.0.7
├─ bplist-parser@0.1.1
├─ brace-expansion@1.1.11
├─ braces@2.3.2
├─ bser@2.1.0
├─ buffer-crc32@0.2.13
├─ bytes@3.0.0
├─ cache-base@1.0.1
├─ caller-callsite@2.0.0
├─ caller-path@2.0.0
├─ capture-exit@2.0.0
├─ chardet@0.4.2
├─ ci-info@2.0.0
├─ class-utils@0.3.6
├─ cli-spinners@2.2.0
├─ cli-width@2.2.0
├─ cliui@3.2.0
├─ clone@1.0.4
├─ code-point-at@1.1.0
├─ collection-visit@1.0.0
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ color-support@1.1.3
├─ colorette@1.1.0
├─ commander@2.20.0
├─ commondir@1.0.1
├─ compressible@2.0.17
├─ compression@1.7.4
├─ concat-map@0.0.1
├─ concat-stream@1.6.2
├─ convert-source-map@1.6.0
├─ copy-descriptor@0.1.1
├─ core-js@2.6.9
├─ core-util-is@1.0.2
├─ cosmiconfig@5.2.1
├─ create-react-class@15.6.3
├─ cross-spawn@5.1.0
├─ dayjs@1.8.16
├─ debug@2.6.9
├─ decode-uri-component@0.2.0
├─ deepmerge@3.3.0
├─ defaults@1.0.3
├─ define-properties@1.1.3
├─ denodeify@1.2.1
├─ destroy@1.0.4
├─ dom-walk@0.1.1
├─ ee-first@1.1.1
├─ encoding@0.1.12
├─ end-of-stream@1.4.1
├─ envinfo@7.3.1
├─ error-ex@1.3.2
├─ errorhandler@1.5.1
├─ esprima@4.0.1
├─ esutils@2.0.3
├─ etag@1.8.1
├─ event-target-shim@5.0.1
├─ eventemitter3@3.1.2
├─ expand-brackets@2.1.4
├─ external-editor@2.2.0
├─ extglob@2.0.4
├─ fancy-log@1.3.3
├─ fbjs-css-vars@1.0.2
├─ fbjs-scripts@1.2.0
├─ figures@2.0.0
├─ fill-range@4.0.0
├─ finalhandler@1.1.2
├─ find-cache-dir@2.1.0
├─ for-in@1.0.2
├─ fresh@0.5.2
├─ fs-extra@7.0.1
├─ fs.realpath@1.0.0
├─ function-bind@1.1.1
├─ get-stream@4.1.0
├─ get-value@2.0.6
├─ glob@7.1.4
├─ global@4.4.0
├─ growly@1.3.0
├─ has-symbols@1.0.0
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ hermesvm@0.1.1
├─ hosted-git-info@2.8.4
├─ http-errors@1.7.3
├─ iconv-lite@0.4.24
├─ image-size@0.6.3
├─ import-fresh@2.0.0
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ inquirer@3.3.0
├─ invert-kv@1.0.0
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.2.1
├─ is-ci@2.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-directory@0.3.1
├─ is-plain-object@2.0.4
├─ is-promise@2.1.0
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jest-get-type@24.9.0
├─ jest-message-util@24.9.0
├─ jest-mock@24.9.0
├─ jest-serializer@24.9.0
├─ jest-util@24.9.0
├─ jest-validate@24.9.0
├─ jest-worker@24.9.0
├─ jetifier@1.6.4
├─ js-tokens@4.0.0
├─ js-yaml@3.13.1
├─ jsc-android@245459.0.0
├─ jsesc@2.5.2
├─ json-parse-better-errors@1.0.2
├─ json-stable-stringify@1.0.1
├─ json5@2.1.0
├─ jsonfile@4.0.0
├─ klaw@1.3.1
├─ lcid@1.0.0
├─ leven@3.1.0
├─ load-json-file@2.0.0
├─ locate-path@3.0.0
├─ lodash@4.17.15
├─ log-symbols@2.2.0
├─ logkitty@0.6.1
├─ loose-envify@1.4.0
├─ lru-cache@4.1.5
├─ make-dir@2.1.0
├─ makeerror@1.0.11
├─ map-age-cleaner@0.1.3
├─ map-visit@1.0.0
├─ mem@1.1.0
├─ merge-stream@1.0.1
├─ metro-babel7-plugin-react-transform@0.54.1
├─ metro-config@0.54.1
├─ metro-inspector-proxy@0.54.1
├─ metro-minify-uglify@0.54.1
├─ metro-react-native-babel-transformer@0.54.1
├─ metro-source-map@0.55.0
├─ metro-symbolicate@0.55.0
├─ metro@0.54.1
├─ mime-db@1.41.0
├─ mime-types@2.1.11
├─ mime@2.4.4
├─ min-document@2.19.0
├─ minimatch@3.0.4
├─ mixin-deep@1.3.2
├─ mkdirp@0.5.1
├─ morgan@1.9.1
├─ ms@2.1.2
├─ mute-stream@0.0.7
├─ nanomatch@1.2.13
├─ negotiator@0.6.2
├─ nice-try@1.0.5
├─ node-fetch@2.6.0
├─ node-int64@0.4.0
├─ node-modules-regexp@1.0.0
├─ node-notifier@5.4.3
├─ normalize-package-data@2.5.0
├─ normalize-path@2.1.1
├─ number-is-nan@1.0.1
├─ ob1@0.55.0
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ object-keys@1.1.1
├─ object.assign@4.1.0
├─ on-headers@1.0.2
├─ once@1.4.0
├─ onetime@2.0.1
├─ open@6.4.0
├─ options@0.0.6
├─ ora@3.4.0
├─ os-locale@2.1.0
├─ os-tmpdir@1.0.2
├─ p-defer@1.0.0
├─ p-is-promise@2.1.0
├─ p-limit@2.2.1
├─ p-locate@3.0.0
├─ p-try@2.2.0
├─ parse-json@4.0.0
├─ parse-node-version@1.0.1
├─ pascalcase@0.1.1
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-parse@1.0.6
├─ path-type@2.0.0
├─ pirates@4.0.1
├─ pkg-dir@3.0.0
├─ plist@3.0.1
├─ plugin-error@0.1.2
├─ posix-character-classes@0.1.1
├─ pretty-format@24.9.0
├─ private@0.1.8
├─ process-nextick-args@2.0.1
├─ process@0.11.10
├─ prop-types@15.7.2
├─ pseudomap@1.0.2
├─ pump@3.0.0
├─ range-parser@1.2.1
├─ react-deep-force-update@1.1.2
├─ react-devtools-core@3.6.3
├─ react-is@16.9.0
├─ react-native@0.60.5
├─ react-proxy@1.1.8
├─ read-pkg-up@2.0.0
├─ read-pkg@2.0.0
├─ readable-stream@2.3.6
├─ regenerate-unicode-properties@8.1.0
├─ regenerator-transform@0.14.1
├─ regexpu-core@4.6.0
├─ regjsgen@0.5.0
├─ regjsparser@0.6.0
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.3
├─ resolve-from@3.0.0
├─ resolve-url@0.2.1
├─ resolve@1.12.0
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ rimraf@2.7.1
├─ rsvp@4.8.5
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ rxjs@5.5.12
├─ safer-buffer@2.1.2
├─ sane@4.1.0
├─ sax@1.2.4
├─ scheduler@0.14.0
├─ semver@5.7.1
├─ send@0.17.1
├─ serialize-error@2.1.0
├─ serve-static@1.14.1
├─ set-blocking@2.0.0
├─ set-value@2.0.1
├─ setprototypeof@1.1.1
├─ shebang-regex@1.0.0
├─ shell-quote@1.6.1
├─ shellwords@0.1.1
├─ signal-exit@3.0.2
├─ simple-plist@1.0.0
├─ slice-ansi@2.1.0
├─ slide@1.1.6
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.2
├─ source-map-support@0.5.13
├─ source-map-url@0.4.0
├─ spdx-correct@3.1.0
├─ spdx-exceptions@2.2.0
├─ split-string@3.1.0
├─ sprintf-js@1.0.3
├─ stack-utils@1.0.2
├─ stacktrace-parser@0.1.7
├─ static-extend@0.1.2
├─ statuses@1.5.0
├─ stream-buffers@2.2.0
├─ string_decoder@1.1.1
├─ string-width@2.1.1
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ supports-color@5.5.0
├─ symbol-observable@1.0.1
├─ temp@0.8.3
├─ throat@4.1.0
├─ through@2.3.8
├─ through2@2.0.5
├─ time-stamp@1.1.0
├─ tmp@0.0.33
├─ tmpl@1.0.4
├─ to-fast-properties@2.0.0
├─ to-object-path@0.3.0
├─ to-regex-range@2.1.1
├─ toidentifier@1.0.0
├─ trim-right@1.0.1
├─ type-fest@0.7.1
├─ typedarray@0.0.6
├─ uglify-es@3.3.9
├─ ultron@1.0.2
├─ unicode-canonical-property-names-ecmascript@1.0.4
├─ unicode-match-property-ecmascript@1.0.4
├─ unicode-match-property-value-ecmascript@1.1.0
├─ unicode-property-aliases-ecmascript@1.0.5
├─ union-value@1.0.1
├─ universalify@0.1.2
├─ unpipe@1.0.0
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ use@3.1.1
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.1
├─ uuid@3.3.3
├─ validate-npm-package-license@3.0.4
├─ vary@1.1.2
├─ walker@1.0.7
├─ wcwidth@1.0.1
├─ whatwg-fetch@3.0.0
├─ which@1.3.1
├─ write-file-atomic@1.3.4
├─ xcode@2.0.0
├─ xmlbuilder@9.0.7
├─ xmldoc@1.1.2
├─ xmldom@0.1.27
├─ xpipe@1.0.5
├─ xtend@4.0.2
├─ y18n@3.2.1
└─ yargs-parser@7.0.0
Done in 6.82s.
info Setting up new React Native app in /xxxxxxxxx/UiKittenTS
info Fetching template react-native-template-ui-kitten-typescript...
yarn add v1.17.3
[1/4] Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @react-native-community/eslint-config@0.0.3" has unmet peer dependency "eslint@>=5".
warning "@react-native-community/eslint-config > eslint-plugin-eslint-comments@3.1.2" has unmet peer dependency "eslint@>=4.19.1".
warning "@react-native-community/eslint-config > babel-eslint@10.0.1" has unmet peer dependency "eslint@>= 4.12.1".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-hooks@1.7.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-jest@22.4.1" has unmet peer dependency "eslint@>=5".
warning "@react-native-community/eslint-config > eslint-plugin-flowtype@2.50.3" has unmet peer dependency "eslint@>=2.0.0".
[4/4] Building fresh packages...
error /xxxxxxxxx/UiKittenTS/node_modules/react-native-template-ui-kitten-typescript: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /xxxxxxxxx/UiKittenTS/node_modules/react-native-template-ui-kitten-typescript
Output:
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/xxxxxxxxx/UiKittenTS/node_modules/react-native-template-ui-kitten-typescript/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.17.3
[1/2] Removing module react-native-template-ui-kitten-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-ui-kitten-typescript. This is not a critical error, you can work on your app.
(node:3435) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-ui-kitten-typescript
    at makeError (/xxxxxxxxx/UiKittenTS/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/xxxxxxxxx/UiKittenTS/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3435) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by artyorsh** [comment]
We've already faced this issue and started working on it. Thanks for reporting

**Comment by androidjaijai** [comment]
Thanks @artyorsh !

**Comment by artyorsh** [comment]
Anyone facing this issue, please follow [this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-into-existing-app#add-into-existing-project). We got this fixed in #623 and it will be available soon in v4.2 stable

**Comment by 5etar** [comment]
The guide you provide : Page does not exist.

**Comment by artyorsh** [comment]
@5etar thanks. Updated
