### ISSUE TITLE
Install not working?

### ISSUE THREAD

**Issue by kaidoj** [akveo/react-native-ui-kitten#850]
## 🐛 Bug Report

Could not install.

## To Reproduce

npx react-native init MyApp --template @ui-kitten/template-ts

## Expected behavior

Throws error. Never finishes.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

Node version 10.16.3
npx version 6.9.0
```
info Fetching template react-native-template-@ui-kitten/template-js...
npm ERR! Error while executing:
npm ERR! \mygitpath\git.EXE ls-remote -h -t ssh://git@github.com/ui-kitten/template-js.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
```

```
(node:17084) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --save --save-exact react-native-template-@ui-kitten/template-js
    at makeError (mypath\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (mypath\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by artyorsh** [comment]
You're using an outdated CLI: https://github.com/akveo/react-native-ui-kitten/issues/690#issuecomment-543794472
