### ISSUE TITLE
Module parse failed: Unexpected token. You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by harryy2510** [akveo/react-native-ui-kitten#996]
## 🐛 Bug Report

Not able to build code 

![image](https://user-images.githubusercontent.com/7416971/78830030-f2c9f100-7a04-11ea-81e1-e742854bb48d.png)

![image](https://user-images.githubusercontent.com/7416971/78830051-f9f0ff00-7a04-11ea-8c40-af2c01a1cdb0.png)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    ^2.0.0-alpha.1    |
| @ui-kitten/components   |    ^5.0.0-alpha.1     |

## Environment information

```bash
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.4 - ~/.yvm/shim/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
```

**Comment by lesmo** [comment]
Feels like a duplicate of #991. You're trying to use `ui-kitten` in `react-native-web` (or `expo-web` in this case), and you need to make Webpack transpile `node_modules` or you'll face these kinds of errors.

You'll have to add something like this in `babel.config` file:
```js
module: {
  rules: [
    // This would match almost any react-native module
    {
      test: /(@?react-(navigation|native)).*\.(ts|js)x?$/,
      include: /node_modules/,
      exclude: [/react-native-web/, /\.(native|ios|android)\.(ts|js)x?$/],
      loader: 'babel-loader'
    },
    // This would match ui-kitten
    {
        test: /@?(ui-kitten|eva-design).*\.(ts|js)x?$/,
        loader: 'babel-loader'
    }
  ]
}
```

**Comment by harryy2510** [comment]
This code snippet is for `webpack.config` I believe instead of `babel.config`

For now, I've used installed `@expo/webpack-config` packages which let us modify the webpack file, created `webpack.config` at root level and added this code snippet

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path')

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);
    config.module.rules.forEach(r => {
        if (r.oneOf) {
            r.oneOf.forEach(o => {
                if (o.use && o.use.loader && o.use.loader.includes('babel-loader')) {
                    o.include = [
                        path.resolve('.'),
                        path.resolve('node_modules/@ui-kitten/components'),
                    ]
                }
            })
        }
    })
    return config;
};

```

I know this code snippet is not much cleaner. Any suggestions regarding this approach are much appreciated. Thanks! :)

**Comment by artyorsh** [comment]
@harryy2510 @lesmo 
This is a library build issue. We moved to ts3.8 without thinking about option chaining transpiling. [Here](https://github.com/kulshekhar/ts-jest/issues/1283#issuecomment-572412196) seems like a correct way to fix this, should be done on the ui kitten side.

Thanks for sharing workarounds 👍

**Comment by the-phoenix** [comment]
@artyorsh I saw you've upgraded to ts3.8 in `v5.0.0-alpha.1` release but it still didn't fix above issue. 
Would you please check?

**Comment by artyorsh** [comment]
> @artyorsh I saw you've upgraded to ts3.8 in `v5.0.0-alpha.1` release but it still didn't fix above issue. 
> 
> Would you please check?

Use the workaround by @harryy2510 as a temporary solution.
This definitely will be fixed in alpha.2, but no ETAs to be honest

**Comment by temitopealabi** [comment]
@harryy2510  thanks your suggestion work for me

**Comment by harryy2510** [comment]
I went through the documentation and found that `@expo/webpack-config` already gives option to add paths to babel config. Now the config looks mych better. Here's the updated config


```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path')

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync({
        ...env,
        babel: {
            dangerouslyAddModulePathsToTranspile: [
                path.resolve('.'),
                path.resolve('node_modules/@ui-kitten/components'),
            ]
        }
    }, argv);
    return config;
};

```

**Comment by artyorsh** [comment]
Since this is a workaround and we can do nothing about that (excluding possible changes in the build process, which is not an issue), I think I will do nothing on this issue for the package distributed with `latest` npm tag (which is default when you run `npm install`).

Despite this, I will make a separate tag to distribute the package bundled with outdated build system just to make it compatible with webpack / acorn.

The new package will be published together with v5 stable (you may track it [here](https://github.com/akveo/react-native-ui-kitten/pull/1055)) and installable with
`npm i @ui-kitten/components@ts3.7` until [this issue will be fixed in acorn](https://github.com/acornjs/acorn/pull/891).

**Comment by Roeefl** [comment]
@harryy2510 Thanks, this solution works well.

For anyone encountering this issue, I'm just gonna lay out the entire process in steps:
1. run `expo install @expo/webpack-config`
2. create 'webpack.config.js' file at root level
3. add the last code snippet provided by @harryy2510. that's all this file should contain

**Comment by jasuno** [comment]
@harryy2510 I added that snipped to my webpack.config.js but the problem persists, any other work around?

**Comment by harryy2510** [comment]
@jasuno Can you share the screenshot of exactly what error you are getting? It maybe due to some other module and You might need to add that module too in your webpack config for babel to transform it

**Comment by harryy2510** [comment]
@jasuno 
If I'm correct
1. You've installed expo webpack config `npm i @expo/webpack-config`
2. You've created a webpack.config.js file in the root folder of your project?
And its content should be

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync({
        ...env,
        babel: {
            dangerouslyAddModulePathsToTranspile: ['@ui-kitten/components']
        }
    }, argv);
    return config;
};
```

**Comment by jasuno** [comment]
Thank you very much that actually helped out, I was changing the one in my node modules... yeah I know a silly mistake

**Comment by adammcarth** [comment]
This also causes issues for Jest and [React Test Renderer](https://reactjs.org/docs/test-renderer.html) when testing components which import anything from `@ui-kitten/components`.

```
 FAIL  src/screens/Login/Login.test.tsx
   - Test suite failed to run

Jest encountered an unexpected token

Details:

    ./../node_modules/@ui-kitten/components/ui/autocomplete/autocomplete.component.ts:95
                this.popoverRef.current?.show();
                                        ^

    SyntaxError: Unexpected token '.'
```

How on earth is TypeScript specific syntax even making it to the distribution build in the first place? That's surely not the desired output, right?

**Comment by harryy2510** [comment]
@adammcarth 
Hi, I think instead of accusing, we can always find a solution to the problem and alwasy praise the efforts and time UI Kitten team has put up.

Firstly, It is not a typescript specific syntax now. It has been introduced to Javascript also and you'll start to find more of this syntax in near future in almost every project. You can read more about it here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Secondly, What you can do is use babel transform in your jest config and use this plugin
https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining

**Comment by adammcarth** [comment]
Thanks for the info @harryy2510. I genuinely had no idea the `?.` operator had made it to the JavaScript core 🤷‍♀️

My follow up questions are still going to be quite similar though. Why isn't UI Kitten transpiling down to ES5 JavaScript? What are the benefits of remaining at ES Next and requiring projects to use additional Babel plugins when (I assume) it could just be transpiled to ES5 for increased support and flexibility?

The reason I'm asking these questions is because I'm happy to help make those changes if it was just an initial oversight. They weren't meant to come off as accusations; apologies to everyone if they did 👍

**Comment by harryy2510** [comment]
@adammcarth 
I think UI Kitten team will be better able to answer this question. No hard feelings though :)

**Comment by pherm** [comment]
> @adammcarth
> I think UI Kitten team will be better able to answer this question. No hard feelings though :)

i have some error. I'm not working with expo. Any fix? 

Ps. "@ui-kitten/components": "^5.0.0"

**Comment by pherm** [comment]
@artyorsh i fix, thank you for support! Ps. I'm working with next js and rnw and kitten ui

**Comment by jmakGH** [comment]
Is anyone else running into this issue when using Typescript and Expo?

**Comment by JordiOrriols** [comment]
Me!

Using expo and typescript. I just started with the instructions on the "get started" documentation, and I got the error of this issue.

I'm currently using:

```
   "@eva-design/eva": "^2.0.0",
   "@ui-kitten/components": "^5.0.0",
```

**Comment by eunhyoung0313** [comment]
I've tried the solution above and fixed "missing appropriate loader " issue, but I still have an error message 


 " Module parse failed: Unexpected token (110:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'C:\Users\Admin\Desktop\intern\delight\node_modules\.staging\webpack-613473b9\hot'
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.<anonymous> (C:\Users\Admin\Desktop\intern\delight\node_modules\sane\src\node_watcher.js:291:16)
    at FSReqCallback.oncomplete (fs.js:168:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\Users\\Admin\\Desktop\\intern\\delight\\node_modules\\.staging\\webpack-613473b9\\hot'
}
" 
What should I do?

**Comment by harryy2510** [comment]
@eunhyoung0313 @JordiOrriols 


> ### Steps
> 1. Install expo webpack config dependency
>    `npm i -D @expo/webpack-config`
> 2. Create `webpack.config.js` in the root folder of the project and add the code snippet below
> 
> ```
> const createExpoWebpackConfigAsync = require('@expo/webpack-config');
> 
> module.exports = async function(env, argv) {
>     const config = await createExpoWebpackConfigAsync({
>         ...env,
>         babel: {
>             dangerouslyAddModulePathsToTranspile: ['@ui-kitten/components']
>         }
>     }, argv);
>     return config;
> };
> ```

**Comment by radihuq** [comment]
I managed to get this to work on a Create React Application by using the documentation from [React Native Elements - Usage on the Web](https://reactnativeelements.com/docs/web_usage/)

---

### Install UI Kitten components

 `yarn add @eva-design/eva @ui-kitten/components react-native-svg`

### Install packages to override webpack config

 `yarn add -D @babel/plugin-proposal-class-properties customize-cra react-app-rewired`

### config-overrides.js

Create a new file called `config-overrides.js` in the root of the project and add the following code inside:

```
const path = require('path');
const { override, addBabelPlugins, babelInclude } = require('customize-cra');

module.exports = override(
    ...addBabelPlugins('@babel/plugin-proposal-class-properties'),
    babelInclude([
        // MONOREPO WITH HOIST
        // path.resolve(__dirname, '../../../node_modules/@ui-kitten'),
        // path.resolve(__dirname, '../../../node_modules/@eva-design'),
        path.resolve(__dirname, './node_modules/@ui-kitten'),
        path.resolve(__dirname, './node_modules/@eva-design'),
        path.resolve(__dirname, 'src'),
    ]),
);
```

### Update start script

Update the `start` script in `package.json` to:

`"start": "react-app-rewired start"`

### See if it works

Update `App.tsx` to:

```
import React from 'react';

import { View, Text } from 'react-native';
import * as eva from '@eva-design/eva';
import { ApplicationProvider, Button, Toggle } from '@ui-kitten/components';

type AppProps = {};

export const App: React.FC<AppProps> = () => {
    return (
        <ApplicationProvider {...eva} theme={eva.light}>
            <View>
                <Text>Web App Text</Text>
                <Button>This Button</Button>
                <Toggle>
                    {(evaProps) => <Text {...evaProps}>Place your Text</Text>}
                </Toggle>
            </View>
        </ApplicationProvider>
    );
};
```

**Comment by augsteyer** [comment]
The workaround seems to be working. Just make sure to restart your stack after making the changes.

I am fairly new to it all, so I don't have any hope of figuring out how to solve the actual issue in a PR. I do, however, not mind doing some leg work to get to replicability.

Question regarding this quirk. I was running a basic [tutorial](https://justinnoel.dev/2019/12/21/create-universal-react-native-apps-using-expo-for-web-and-ui-kitten/) from last year using Expo + UI Kitten (v4 at the time). The setup is fairly simple:
```shell
expo init uiKittenStartExpo # I chose Managed Blank TypeScript
cd uiKittenStartExpo
expo install @ui-kitten/eva-icons @eva-design/eva @ui-kitten/components react-native-svg # I downgraded the SVG version to what UI Kitten supports later on (^9.13.6)
expo start
// import "@ui-kitten/components" to App.tsx or App.js with ApplicationProvider and all that stuff
```
One might see that it works on Native app emulators, but not Web. I get that token error that is mentioned by others.
I tried downgrading to version UIKitten v4.4.1 and Eva 1.4.0 and it worked without issues. So I understand why the tutorial worked. Something that changed in v5 possibly broke this expo-kitten relationship.

I also tried the same on their snack.expo.io site, it was complaining at first, but it is working without the needed webpack workaround in their Web view and Native apps. Now I wonder if this can be replicated by others on their machines?

If it is a problem for everyone, should we therefore ask Expo to fix it in the webpack config as they have direct access to it? Or is it in UI Kitten's ballpark to fix?

**Comment by 0plus1** [comment]
After following @harryy2510 I now get:

```
Module parse failed: Unexpected token (1:7)
File was processed with these loaders:
 * ../../../babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> export ActivityBar from "./ActivityBar";
| export ReactionBar from "./ReactionBar";
```

**Comment by darcstar-solutions** [comment]
Adding the following underneath the "web" key in app.json also resolves the issue:
`"build": {
        "babel": {
          "include": [
            "@ui-kitten/components"
          ]
        }`

**Comment by LadislavBohm** [comment]
It would be great if someone know how to configure webpack on an app without Expo.

**Comment by siarheipashkevich** [comment]
Hi @harryy2510 I've followed your steps, but I'm getting an error:
```
(node:22535) UnhandledPromiseRejectionWarning: TypeError: tapable_1.AsyncSeriesWaterfallHook is not a constructor
```

**Comment by atemp21** [comment]
> It would be great if someone know how to configure webpack on an app without Expo.

Here's how to configure you webpack with expo.

first, run `npm install @expo/webpack-config`

create a `webpack.config.js` file in the root of your app

paste this:
`const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path')

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);
    config.module.rules.forEach(r => {
        if (r.oneOf) {
            r.oneOf.forEach(o => {
                if (o.use && o.use.loader && o.use.loader.includes('babel-loader')) {
                    o.include = [
                        path.resolve('.'),
                        path.resolve('node_modules/@ui-kitten/components'),
                    ]
                }
            })
        }
    })
    return config;
};`

now you should be able to setup your App.js or App.tsx file with ui-kitten and eva.

**Comment by pabariyash** [comment]
helllo guys . i am facing an issue in angular. 

when i try to build application at that time get an some error like this please some one can figure out.



`Module parse failed: Unexpected token (47:438)
File was processed with these loaders:
 node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
 node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
`
`var pd_0 = (i1.ɵnov(_v, 29)._handleInput($event.target.value) !== false)
src/app/main/job-rating/job-rating.module.ngfactory.js 19:0-55 90:585-611
_lazy_route_resource lazy namespace object
node_modules/@angular/core/fesm2015/core.js
 src/main.ts
`

**Comment by pabariyash** [comment]
helllo guys . i am facing an issue in angular.

when i try to build application at that time get an some error like this please some one can figure out.

> `Module parse failed: Unexpected token
File was processed with these loaders`

` ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js ./node_modules/@ngtools/webpack/src/index.js`

> You may need an additional loader to handle the result of these loaders.

**Comment by LadislavBohm** [comment]
@pabariyash Why are you posting this here when you are using angular? This is an issue with a specific library for React Native and has nothing to do with your setup and framework.

**Comment by pabariyash** [comment]
@LadislavBohm but problem is same. react , vue or whatever problem .

**Comment by nnnoel** [comment]
If you're trying to get this to work with expo + nextjs, this worked for me:

```js
// next.config.js

const { withExpo } = require('@expo/next-adapter');
const { withUnimodules } = require('@expo/webpack-config/addons');

module.exports = withExpo({
  webpack: (config) => {
    const configWithExpo = withUnimodules(config, {
      projectRoot: __dirname,
      babel: {
        dangerouslyAddModulePathsToTranspile: [
          '@ui-kitten',
        ],
      },
    });
    return configWithExpo
  },
});
```

**Comment by elisjoaquim** [comment]
Thanks @harryy2510 ! Yoursuggestions works great.

**Comment by belaziv** [comment]
> Adding the following underneath the "web" key in app.json also resolves the issue:
> "build": { "babel": { "include": [ "@ui-kitten/components" ] }

@darcstar-solutions Can you please specify where exactly to add it? ty

**Comment by belaziv** [comment]
If I add [that](https://github.com/akveo/react-native-ui-kitten/issues/991#issuecomment-610511495) I get the following error:
```
ERROR in ./src/App.tsx 29:2
Module parse failed: Unexpected token (29:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const HomeScreen = () => (
>   <Layout style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
|     <Text category='h1'>HOME</Text>
|   </Layout>
 @ ./src/index.tsx 2:0-24 4:43-46
```
Any idea?

**Comment by shamaz332** [comment]
change react-scripts version in package.json to "react-scripts": "^4.0.3" . create-react-app is not pulling the correct version that's why you are facing this issue.

**Comment by AnkittSharmaa** [comment]
```
./src/Checkout.js 59:21
Module parse failed: Unexpected token (59:21)
You may need an appropriate loader to handle this file type.
|       columnNumber: 11
|     }
>   }, "Hello, ", user**?**.email), /*#__PURE__*/React.createElement("h2", {
|     className: "checkout__title",
|     __self: this,
```

I am getting this error in my console.

**Comment by harryy2510** [comment]
> ```
> ./src/Checkout.js 59:21
> Module parse failed: Unexpected token (59:21)
> You may need an appropriate loader to handle this file type.
> |       columnNumber: 11
> |     }
> >   }, "Hello, ", user**?**.email), /*#__PURE__*/React.createElement("h2", {
> |     className: "checkout__title",
> |     __self: this,
> ```
> 
> I am getting this error in my console.

Are you trying to use `h2` in react native code?  🤔

**Comment by harryy2510** [comment]
> If I add [that](https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-611254630) I get the following error:
> 
> ```
> ERROR in ./src/App.tsx 29:2
> Module parse failed: Unexpected token (29:2)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | 
> | const HomeScreen = () => (
> >   <Layout style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
> |     <Text category='h1'>HOME</Text>
> |   </Layout>
>  @ ./src/index.tsx 2:0-24 4:43-46
> ```
> 
> Any idea?

Did you try this?
https://github.com/akveo/react-native-ui-kitten/issues/996#issuecomment-645448007

**Comment by Athiban-32** [comment]
> ## 🐛 Bug Report
> Not able to build code
> 
> ![image](https://user-images.githubusercontent.com/7416971/78830030-f2c9f100-7a04-11ea-81e1-e742854bb48d.png)
> 
> ![image](https://user-images.githubusercontent.com/7416971/78830051-f9f0ff00-7a04-11ea-8c40-af2c01a1cdb0.png)
> 
> ## UI Kitten and Eva version
> Package	Version
> @eva-design/eva	^2.0.0-alpha.1
> @ui-kitten/components	^5.0.0-alpha.1
> ## Environment information
> ```shell
>   System:
>     OS: macOS 10.15.3
>     CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
>   Binaries:
>     Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
>     Yarn: 1.22.4 - ~/.yvm/shim/yarn
>     npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK:
>       API Levels: 27, 28
>       Build Tools: 27.0.3, 28.0.3, 29.0.3
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.6010548
>     Xcode: 11.4/11E146 - /usr/bin/xcodebuild
>   npmPackages:
>     react: ~16.13.1 => 16.13.1 
>     react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
> ```

<img width="740" alt="Screenshot 2022-08-15 003934" src="https://user-images.githubusercontent.com/93418753/184551365-910f974e-1a15-44c6-847c-d8c2c222e207.png">

the same error has occurred for me right now !! could you please resolve my bugs so that it would be helpful for me

**Comment by Athiban-32** [comment]
Can Anyone say why this error is occurring in the code and I fixed it by adding webpack-config.js after that also the code is showing an error...

**Comment by mzeesha** [comment]
![Module Parse Failed Error! ](https://user-images.githubusercontent.com/101974988/188907289-0761da7f-bb11-47f6-ac6a-9c48e1f6c447.png)

**Comment by mzeesha** [comment]
I have stuck with the module parse failed error while adding Toast-Notification in my react-app.
Please help me out! if anyone has any idea about handling this error

**Comment by jbmarflo** [comment]
> This code snippet is for `webpack.config` I believe instead of `babel.config`
> 
> For now, I've used installed `@expo/webpack-config` packages which let us modify the webpack file, created `webpack.config` at root level and added this code snippet
> 
> ```
> const createExpoWebpackConfigAsync = require('@expo/webpack-config');
> const path = require('path')
> 
> module.exports = async function(env, argv) {
>     const config = await createExpoWebpackConfigAsync(env, argv);
>     config.module.rules.forEach(r => {
>         if (r.oneOf) {
>             r.oneOf.forEach(o => {
>                 if (o.use && o.use.loader && o.use.loader.includes('babel-loader')) {
>                     o.include = [
>                         path.resolve('.'),
>                         path.resolve('node_modules/@ui-kitten/components'),
>                     ]
>                 }
>             })
>         }
>     })
>     return config;
> };
> ```
> 
> I know this code snippet is not clean. Any suggestions regarding this approach are much appreciated. Thanks! :)

Hi, I have the same error but with NUXT. I put @expo/webpack-config and created webpack.config. But not work yet. 

![image](https://user-images.githubusercontent.com/12074969/217924931-7df5b2b5-e0d9-4b1e-8531-0b579f7f1d90.png)
![image](https://user-images.githubusercontent.com/12074969/217924990-b792c4d7-f7d9-4290-a769-c4ebc92ae72d.png)

**Comment by abhijith1741** [comment]
hey while importing query-string in react it showing an error:
./node_modules/query-string/base.js 424:161
Module parse failed: Unexpected token (424:161)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   return {
>     url: ((_url_ = url_) === null || _url_ === void 0 ? void 0 : (_url_$split = _url_.split('?')) === null || _url_$split === void 0 ? void 0 : _url_$split[0]) ?? '',
|     query: parse(extract(url), options),
|     ...(options && options.parseFragmentIdentifier && hash ? {

**Comment by Karthikaddagalla** [comment]
Thanks @harryy2510 it works. For anyone to whom his solution is not working. Dont forget to replace the package name inside 
dangerouslyAddModulePathsToTranspile key.

            dangerouslyAddModulePathsToTranspile: ['@package_name']

**Comment by NabiiBux** [comment]
I am getting this error Please Help me to Fix This  on Windows 10
while running the command Npm Start or Yarn Start 

Node version. v18.16.1
Npm Version. 9.5.1
Yarn Version. 1.22.19

Failed to compile.
./node_modules/@noble/curves/abstract/weierstrass.js 1016:57
Module parse failed: Unexpected token (1016:57)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     const u1 = modN(h * is); // u1 = hs^-1 mod n
|     const u2 = modN(r * is); // u2 = rs^-1 mod n
>     const R = Point.BASE.multiplyAndAddUnsafe(P, u1, u2)?.toAffine(); // R = u1⋅G + u2⋅P
|     if (!R) return false;
|     const v = modN(R.x);



![123](https://github.com/akveo/react-native-ui-kitten/assets/29281694/1424e363-f76a-4848-a09e-1837d25bac28)

**Comment by JeffXu1** [comment]
> I am getting this error Please Help me to Fix This on Windows 10 while running the command Npm Start or Yarn Start
> 
> Node version. v18.16.1 Npm Version. 9.5.1 Yarn Version. 1.22.19
> 
> Failed to compile. ./node_modules/@noble/curves/abstract/weierstrass.js 1016:57 Module parse failed: Unexpected token (1016:57) File was processed with these loaders:
> 
> * ./node_modules/babel-loader/lib/index.js
>   You may need an additional loader to handle the result of these loaders.
>   |     const u1 = modN(h * is); // u1 = hs^-1 mod n
>   |     const u2 = modN(r * is); // u2 = rs^-1 mod n
> 
> > ```
> > const R = Point.BASE.multiplyAndAddUnsafe(P, u1, u2)?.toAffine(); // R = u1⋅G + u2⋅P
> > ```
> 
> | if (!R) return false; | const v = modN(R.x);
> 
> ![123](https://private-user-images.githubusercontent.com/29281694/285615251-1424e363-f76a-4848-a09e-1837d25bac28.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODMzMzUsIm5iZiI6MTcwNTQ4MzAzNSwicGF0aCI6Ii8yOTI4MTY5NC8yODU2MTUyNTEtMTQyNGUzNjMtZjc2YS00ODQ4LWEwOWUtMTgzN2QyNWJhYzI4LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA5MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNDkzMTVjZjkwNDUxMTFiZDE0OWUzOTMwMjhkNDM4NjIxYmZiNGRkY2I4ZGE5ODdhODhmZjM1Mzc4ZTM0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BmFZXxxBFnvnyCR_qFdPMwIg9ss2CRGfrq9Vxy_fyA)

do you solve this issue?

**Comment by bataevvlad** [comment]
This has been addressed in the upcoming release. The build infrastructure has been completely modernized — we now use react-native-builder-bob with ESM modules and Turborepo for orchestration. Module resolution issues like this should no longer occur. Beta release coming soon!
